version: '3.8'

services:
  # 1. Service Database (MongoDB)
  database:
    image: mongo:latest
    container_name: pettycash-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Agar data tidak hilang saat container direstart
    networks:
      - app-network

  # 2. Service Backend (Node.js/GraphQL)
  backend:
    build: ./backend
    container_name: pettycash-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      # PENTING: Di sini kita mengganti 'localhost' dengan nama service database ('database')
      - MONGO_URI=mongodb://database:27017/pettycash
    depends_on:
      - database # Backend baru jalan setelah database siap
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge